name = "Minecraft: Vanilla+"
author = "Polyeons"
version = "v0.1.6b"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "91fd2dd3b108c2b68d1ea65592d7d037f5d61e58216764eb224d79179cfe71eb"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
