name = "Minecraft: Vanilla+"
author = "Polyeons"
version = "v0.1.6b"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d3580e484c60ba259fc151c13030696618dbd7e811d5054718779bfe6aa11594"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
